package com.nhn.www.event.bean;

import java.util.Date;

public class BannerEventResultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_result.sno
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    private Long sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_result.day
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    private Date day;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_result.sno
     *
     * @return the value of banner_event_result.sno
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    public Long getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_result.sno
     *
     * @param sno the value for banner_event_result.sno
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    public void setSno(Long sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_result.day
     *
     * @return the value of banner_event_result.day
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_result.day
     *
     * @param day the value for banner_event_result.day
     *
     * @mbggenerated Wed Apr 26 17:50:13 KST 2017
     */
    public void setDay(Date day) {
        this.day = day;
    }
}