package com.nhn.www.event.bean;

public class BannerEventItemImgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item_img.item_key
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    private Integer itemKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item_img.local
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    private String local;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item_img.item_key
     *
     * @return the value of banner_event_item_img.item_key
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public Integer getItemKey() {
        return itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item_img.item_key
     *
     * @param itemKey the value for banner_event_item_img.item_key
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public void setItemKey(Integer itemKey) {
        this.itemKey = itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item_img.local
     *
     * @return the value of banner_event_item_img.local
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item_img.local
     *
     * @param local the value for banner_event_item_img.local
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public void setLocal(String local) {
        this.local = local;
    }
}