package com.nhn.www.event.bean;

public class BannerEventItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.item_key
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private Integer itemKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.prob
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private Double prob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.descript
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.used
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private String used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.item_serial
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private Integer itemSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.item_type
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private Integer itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item.item_count
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    private Integer itemCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.item_key
     *
     * @return the value of banner_event_item.item_key
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public Integer getItemKey() {
        return itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.item_key
     *
     * @param itemKey the value for banner_event_item.item_key
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setItemKey(Integer itemKey) {
        this.itemKey = itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.prob
     *
     * @return the value of banner_event_item.prob
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public Double getProb() {
        return prob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.prob
     *
     * @param prob the value for banner_event_item.prob
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setProb(Double prob) {
        this.prob = prob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.descript
     *
     * @return the value of banner_event_item.descript
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.descript
     *
     * @param descript the value for banner_event_item.descript
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.used
     *
     * @return the value of banner_event_item.used
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.used
     *
     * @param used the value for banner_event_item.used
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setUsed(String used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.item_serial
     *
     * @return the value of banner_event_item.item_serial
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public Integer getItemSerial() {
        return itemSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.item_serial
     *
     * @param itemSerial the value for banner_event_item.item_serial
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setItemSerial(Integer itemSerial) {
        this.itemSerial = itemSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.item_type
     *
     * @return the value of banner_event_item.item_type
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.item_type
     *
     * @param itemType the value for banner_event_item.item_type
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item.item_count
     *
     * @return the value of banner_event_item.item_count
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item.item_count
     *
     * @param itemCount the value for banner_event_item.item_count
     *
     * @mbggenerated Wed Apr 26 16:14:34 KST 2017
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }
}