package com.nhn.www.event.bean;

public class BannerEventItemImg extends BannerEventItemImgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_event_item_img.url
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_event_item_img.url
     *
     * @return the value of banner_event_item_img.url
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_event_item_img.url
     *
     * @param url the value for banner_event_item_img.url
     *
     * @mbggenerated Wed Apr 26 15:56:35 KST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }
}