package com.nhn.www.event.bean;

import java.util.Date;

public class FlowerEventLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.seq
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.usn
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private Long usn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.item_code
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.local
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private String local;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.result
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_log.regdate
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    private Date regdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.seq
     *
     * @return the value of flower_event_log.seq
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.seq
     *
     * @param seq the value for flower_event_log.seq
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.usn
     *
     * @return the value of flower_event_log.usn
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public Long getUsn() {
        return usn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.usn
     *
     * @param usn the value for flower_event_log.usn
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setUsn(Long usn) {
        this.usn = usn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.item_code
     *
     * @return the value of flower_event_log.item_code
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.item_code
     *
     * @param itemCode the value for flower_event_log.item_code
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.local
     *
     * @return the value of flower_event_log.local
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.local
     *
     * @param local the value for flower_event_log.local
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setLocal(String local) {
        this.local = local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.result
     *
     * @return the value of flower_event_log.result
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.result
     *
     * @param result the value for flower_event_log.result
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_log.regdate
     *
     * @return the value of flower_event_log.regdate
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_log.regdate
     *
     * @param regdate the value for flower_event_log.regdate
     *
     * @mbggenerated Mon Apr 10 19:55:08 KST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
}