package com.nhn.www.event.bean;

public class FlowerEventInfoByDateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_info_bydate.item_code
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_event_info_bydate.by_date
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    private String byDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_info_bydate.item_code
     *
     * @return the value of flower_event_info_bydate.item_code
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_info_bydate.item_code
     *
     * @param itemCode the value for flower_event_info_bydate.item_code
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_event_info_bydate.by_date
     *
     * @return the value of flower_event_info_bydate.by_date
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    public String getByDate() {
        return byDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_event_info_bydate.by_date
     *
     * @param byDate the value for flower_event_info_bydate.by_date
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    public void setByDate(String byDate) {
        this.byDate = byDate;
    }
}