package com.nhn.base.notice.bean;

public class NoticeSub extends NoticeSubKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.title
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.imgAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private String imgaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.linkAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private String linkaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.newPopup
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private Integer newpopup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.del
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.content
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.title
     *
     * @return the value of manage_event_notice_sub.title
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.title
     *
     * @param title the value for manage_event_notice_sub.title
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.imgAddr
     *
     * @return the value of manage_event_notice_sub.imgAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public String getImgaddr() {
        return imgaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.imgAddr
     *
     * @param imgaddr the value for manage_event_notice_sub.imgAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setImgaddr(String imgaddr) {
        this.imgaddr = imgaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.linkAddr
     *
     * @return the value of manage_event_notice_sub.linkAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public String getLinkaddr() {
        return linkaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.linkAddr
     *
     * @param linkaddr the value for manage_event_notice_sub.linkAddr
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setLinkaddr(String linkaddr) {
        this.linkaddr = linkaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.newPopup
     *
     * @return the value of manage_event_notice_sub.newPopup
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public Integer getNewpopup() {
        return newpopup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.newPopup
     *
     * @param newpopup the value for manage_event_notice_sub.newPopup
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setNewpopup(Integer newpopup) {
        this.newpopup = newpopup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.del
     *
     * @return the value of manage_event_notice_sub.del
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.del
     *
     * @param del the value for manage_event_notice_sub.del
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.content
     *
     * @return the value of manage_event_notice_sub.content
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.content
     *
     * @param content the value for manage_event_notice_sub.content
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}