package com.nhn.base.notice.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NoticeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public NoticeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdxIsNull() {
            addCriterion("idx is null");
            return (Criteria) this;
        }

        public Criteria andIdxIsNotNull() {
            addCriterion("idx is not null");
            return (Criteria) this;
        }

        public Criteria andIdxEqualTo(Integer value) {
            addCriterion("idx =", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotEqualTo(Integer value) {
            addCriterion("idx <>", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThan(Integer value) {
            addCriterion("idx >", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("idx >=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThan(Integer value) {
            addCriterion("idx <", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThanOrEqualTo(Integer value) {
            addCriterion("idx <=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxIn(List<Integer> values) {
            addCriterion("idx in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotIn(List<Integer> values) {
            addCriterion("idx not in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxBetween(Integer value1, Integer value2) {
            addCriterion("idx between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("idx not between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxtypeIsNull() {
            addCriterion("idxType is null");
            return (Criteria) this;
        }

        public Criteria andIdxtypeIsNotNull() {
            addCriterion("idxType is not null");
            return (Criteria) this;
        }

        public Criteria andIdxtypeEqualTo(String value) {
            addCriterion("idxType =", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeNotEqualTo(String value) {
            addCriterion("idxType <>", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeGreaterThan(String value) {
            addCriterion("idxType >", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeGreaterThanOrEqualTo(String value) {
            addCriterion("idxType >=", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeLessThan(String value) {
            addCriterion("idxType <", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeLessThanOrEqualTo(String value) {
            addCriterion("idxType <=", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeLike(String value) {
            addCriterion("idxType like", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeNotLike(String value) {
            addCriterion("idxType not like", value, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeIn(List<String> values) {
            addCriterion("idxType in", values, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeNotIn(List<String> values) {
            addCriterion("idxType not in", values, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeBetween(String value1, String value2) {
            addCriterion("idxType between", value1, value2, "idxtype");
            return (Criteria) this;
        }

        public Criteria andIdxtypeNotBetween(String value1, String value2) {
            addCriterion("idxType not between", value1, value2, "idxtype");
            return (Criteria) this;
        }

        public Criteria andType1IsNull() {
            addCriterion("type1 is null");
            return (Criteria) this;
        }

        public Criteria andType1IsNotNull() {
            addCriterion("type1 is not null");
            return (Criteria) this;
        }

        public Criteria andType1EqualTo(Integer value) {
            addCriterion("type1 =", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotEqualTo(Integer value) {
            addCriterion("type1 <>", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThan(Integer value) {
            addCriterion("type1 >", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThanOrEqualTo(Integer value) {
            addCriterion("type1 >=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThan(Integer value) {
            addCriterion("type1 <", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThanOrEqualTo(Integer value) {
            addCriterion("type1 <=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1In(List<Integer> values) {
            addCriterion("type1 in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotIn(List<Integer> values) {
            addCriterion("type1 not in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Between(Integer value1, Integer value2) {
            addCriterion("type1 between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotBetween(Integer value1, Integer value2) {
            addCriterion("type1 not between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andSdateIsNull() {
            addCriterion("Sdate is null");
            return (Criteria) this;
        }

        public Criteria andSdateIsNotNull() {
            addCriterion("Sdate is not null");
            return (Criteria) this;
        }

        public Criteria andSdateEqualTo(Date value) {
            addCriterion("Sdate =", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateNotEqualTo(Date value) {
            addCriterion("Sdate <>", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateGreaterThan(Date value) {
            addCriterion("Sdate >", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateGreaterThanOrEqualTo(Date value) {
            addCriterion("Sdate >=", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateLessThan(Date value) {
            addCriterion("Sdate <", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateLessThanOrEqualTo(Date value) {
            addCriterion("Sdate <=", value, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateIn(List<Date> values) {
            addCriterion("Sdate in", values, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateNotIn(List<Date> values) {
            addCriterion("Sdate not in", values, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateBetween(Date value1, Date value2) {
            addCriterion("Sdate between", value1, value2, "sdate");
            return (Criteria) this;
        }

        public Criteria andSdateNotBetween(Date value1, Date value2) {
            addCriterion("Sdate not between", value1, value2, "sdate");
            return (Criteria) this;
        }

        public Criteria andEdateIsNull() {
            addCriterion("Edate is null");
            return (Criteria) this;
        }

        public Criteria andEdateIsNotNull() {
            addCriterion("Edate is not null");
            return (Criteria) this;
        }

        public Criteria andEdateEqualTo(Date value) {
            addCriterion("Edate =", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateNotEqualTo(Date value) {
            addCriterion("Edate <>", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateGreaterThan(Date value) {
            addCriterion("Edate >", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateGreaterThanOrEqualTo(Date value) {
            addCriterion("Edate >=", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateLessThan(Date value) {
            addCriterion("Edate <", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateLessThanOrEqualTo(Date value) {
            addCriterion("Edate <=", value, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateIn(List<Date> values) {
            addCriterion("Edate in", values, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateNotIn(List<Date> values) {
            addCriterion("Edate not in", values, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateBetween(Date value1, Date value2) {
            addCriterion("Edate between", value1, value2, "edate");
            return (Criteria) this;
        }

        public Criteria andEdateNotBetween(Date value1, Date value2) {
            addCriterion("Edate not between", value1, value2, "edate");
            return (Criteria) this;
        }

        public Criteria andMaintitleIsNull() {
            addCriterion("mainTitle is null");
            return (Criteria) this;
        }

        public Criteria andMaintitleIsNotNull() {
            addCriterion("mainTitle is not null");
            return (Criteria) this;
        }

        public Criteria andMaintitleEqualTo(String value) {
            addCriterion("mainTitle =", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleNotEqualTo(String value) {
            addCriterion("mainTitle <>", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleGreaterThan(String value) {
            addCriterion("mainTitle >", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleGreaterThanOrEqualTo(String value) {
            addCriterion("mainTitle >=", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleLessThan(String value) {
            addCriterion("mainTitle <", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleLessThanOrEqualTo(String value) {
            addCriterion("mainTitle <=", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleLike(String value) {
            addCriterion("mainTitle like", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleNotLike(String value) {
            addCriterion("mainTitle not like", value, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleIn(List<String> values) {
            addCriterion("mainTitle in", values, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleNotIn(List<String> values) {
            addCriterion("mainTitle not in", values, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleBetween(String value1, String value2) {
            addCriterion("mainTitle between", value1, value2, "maintitle");
            return (Criteria) this;
        }

        public Criteria andMaintitleNotBetween(String value1, String value2) {
            addCriterion("mainTitle not between", value1, value2, "maintitle");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andImgaddrIsNull() {
            addCriterion("imgAddr is null");
            return (Criteria) this;
        }

        public Criteria andImgaddrIsNotNull() {
            addCriterion("imgAddr is not null");
            return (Criteria) this;
        }

        public Criteria andImgaddrEqualTo(String value) {
            addCriterion("imgAddr =", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrNotEqualTo(String value) {
            addCriterion("imgAddr <>", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrGreaterThan(String value) {
            addCriterion("imgAddr >", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrGreaterThanOrEqualTo(String value) {
            addCriterion("imgAddr >=", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrLessThan(String value) {
            addCriterion("imgAddr <", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrLessThanOrEqualTo(String value) {
            addCriterion("imgAddr <=", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrLike(String value) {
            addCriterion("imgAddr like", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrNotLike(String value) {
            addCriterion("imgAddr not like", value, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrIn(List<String> values) {
            addCriterion("imgAddr in", values, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrNotIn(List<String> values) {
            addCriterion("imgAddr not in", values, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrBetween(String value1, String value2) {
            addCriterion("imgAddr between", value1, value2, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andImgaddrNotBetween(String value1, String value2) {
            addCriterion("imgAddr not between", value1, value2, "imgaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrIsNull() {
            addCriterion("linkAddr is null");
            return (Criteria) this;
        }

        public Criteria andLinkaddrIsNotNull() {
            addCriterion("linkAddr is not null");
            return (Criteria) this;
        }

        public Criteria andLinkaddrEqualTo(String value) {
            addCriterion("linkAddr =", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrNotEqualTo(String value) {
            addCriterion("linkAddr <>", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrGreaterThan(String value) {
            addCriterion("linkAddr >", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrGreaterThanOrEqualTo(String value) {
            addCriterion("linkAddr >=", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrLessThan(String value) {
            addCriterion("linkAddr <", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrLessThanOrEqualTo(String value) {
            addCriterion("linkAddr <=", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrLike(String value) {
            addCriterion("linkAddr like", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrNotLike(String value) {
            addCriterion("linkAddr not like", value, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrIn(List<String> values) {
            addCriterion("linkAddr in", values, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrNotIn(List<String> values) {
            addCriterion("linkAddr not in", values, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrBetween(String value1, String value2) {
            addCriterion("linkAddr between", value1, value2, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andLinkaddrNotBetween(String value1, String value2) {
            addCriterion("linkAddr not between", value1, value2, "linkaddr");
            return (Criteria) this;
        }

        public Criteria andNewpopupIsNull() {
            addCriterion("newPopup is null");
            return (Criteria) this;
        }

        public Criteria andNewpopupIsNotNull() {
            addCriterion("newPopup is not null");
            return (Criteria) this;
        }

        public Criteria andNewpopupEqualTo(Integer value) {
            addCriterion("newPopup =", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupNotEqualTo(Integer value) {
            addCriterion("newPopup <>", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupGreaterThan(Integer value) {
            addCriterion("newPopup >", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupGreaterThanOrEqualTo(Integer value) {
            addCriterion("newPopup >=", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupLessThan(Integer value) {
            addCriterion("newPopup <", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupLessThanOrEqualTo(Integer value) {
            addCriterion("newPopup <=", value, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupIn(List<Integer> values) {
            addCriterion("newPopup in", values, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupNotIn(List<Integer> values) {
            addCriterion("newPopup not in", values, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupBetween(Integer value1, Integer value2) {
            addCriterion("newPopup between", value1, value2, "newpopup");
            return (Criteria) this;
        }

        public Criteria andNewpopupNotBetween(Integer value1, Integer value2) {
            addCriterion("newPopup not between", value1, value2, "newpopup");
            return (Criteria) this;
        }

        public Criteria andViewnationIsNull() {
            addCriterion("viewNation is null");
            return (Criteria) this;
        }

        public Criteria andViewnationIsNotNull() {
            addCriterion("viewNation is not null");
            return (Criteria) this;
        }

        public Criteria andViewnationEqualTo(String value) {
            addCriterion("viewNation =", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationNotEqualTo(String value) {
            addCriterion("viewNation <>", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationGreaterThan(String value) {
            addCriterion("viewNation >", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationGreaterThanOrEqualTo(String value) {
            addCriterion("viewNation >=", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationLessThan(String value) {
            addCriterion("viewNation <", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationLessThanOrEqualTo(String value) {
            addCriterion("viewNation <=", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationLike(String value) {
            addCriterion("viewNation like", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationNotLike(String value) {
            addCriterion("viewNation not like", value, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationIn(List<String> values) {
            addCriterion("viewNation in", values, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationNotIn(List<String> values) {
            addCriterion("viewNation not in", values, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationBetween(String value1, String value2) {
            addCriterion("viewNation between", value1, value2, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewnationNotBetween(String value1, String value2) {
            addCriterion("viewNation not between", value1, value2, "viewnation");
            return (Criteria) this;
        }

        public Criteria andViewtypeIsNull() {
            addCriterion("viewType is null");
            return (Criteria) this;
        }

        public Criteria andViewtypeIsNotNull() {
            addCriterion("viewType is not null");
            return (Criteria) this;
        }

        public Criteria andViewtypeEqualTo(Integer value) {
            addCriterion("viewType =", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeNotEqualTo(Integer value) {
            addCriterion("viewType <>", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeGreaterThan(Integer value) {
            addCriterion("viewType >", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewType >=", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeLessThan(Integer value) {
            addCriterion("viewType <", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeLessThanOrEqualTo(Integer value) {
            addCriterion("viewType <=", value, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeIn(List<Integer> values) {
            addCriterion("viewType in", values, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeNotIn(List<Integer> values) {
            addCriterion("viewType not in", values, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeBetween(Integer value1, Integer value2) {
            addCriterion("viewType between", value1, value2, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("viewType not between", value1, value2, "viewtype");
            return (Criteria) this;
        }

        public Criteria andViewjoinIsNull() {
            addCriterion("viewJoin is null");
            return (Criteria) this;
        }

        public Criteria andViewjoinIsNotNull() {
            addCriterion("viewJoin is not null");
            return (Criteria) this;
        }

        public Criteria andViewjoinEqualTo(Integer value) {
            addCriterion("viewJoin =", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinNotEqualTo(Integer value) {
            addCriterion("viewJoin <>", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinGreaterThan(Integer value) {
            addCriterion("viewJoin >", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewJoin >=", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinLessThan(Integer value) {
            addCriterion("viewJoin <", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinLessThanOrEqualTo(Integer value) {
            addCriterion("viewJoin <=", value, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinIn(List<Integer> values) {
            addCriterion("viewJoin in", values, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinNotIn(List<Integer> values) {
            addCriterion("viewJoin not in", values, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinBetween(Integer value1, Integer value2) {
            addCriterion("viewJoin between", value1, value2, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewjoinNotBetween(Integer value1, Integer value2) {
            addCriterion("viewJoin not between", value1, value2, "viewjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinIsNull() {
            addCriterion("viewSjoin is null");
            return (Criteria) this;
        }

        public Criteria andViewsjoinIsNotNull() {
            addCriterion("viewSjoin is not null");
            return (Criteria) this;
        }

        public Criteria andViewsjoinEqualTo(Date value) {
            addCriterion("viewSjoin =", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinNotEqualTo(Date value) {
            addCriterion("viewSjoin <>", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinGreaterThan(Date value) {
            addCriterion("viewSjoin >", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinGreaterThanOrEqualTo(Date value) {
            addCriterion("viewSjoin >=", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinLessThan(Date value) {
            addCriterion("viewSjoin <", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinLessThanOrEqualTo(Date value) {
            addCriterion("viewSjoin <=", value, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinIn(List<Date> values) {
            addCriterion("viewSjoin in", values, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinNotIn(List<Date> values) {
            addCriterion("viewSjoin not in", values, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinBetween(Date value1, Date value2) {
            addCriterion("viewSjoin between", value1, value2, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewsjoinNotBetween(Date value1, Date value2) {
            addCriterion("viewSjoin not between", value1, value2, "viewsjoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinIsNull() {
            addCriterion("viewEjoin is null");
            return (Criteria) this;
        }

        public Criteria andViewejoinIsNotNull() {
            addCriterion("viewEjoin is not null");
            return (Criteria) this;
        }

        public Criteria andViewejoinEqualTo(Date value) {
            addCriterion("viewEjoin =", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinNotEqualTo(Date value) {
            addCriterion("viewEjoin <>", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinGreaterThan(Date value) {
            addCriterion("viewEjoin >", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinGreaterThanOrEqualTo(Date value) {
            addCriterion("viewEjoin >=", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinLessThan(Date value) {
            addCriterion("viewEjoin <", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinLessThanOrEqualTo(Date value) {
            addCriterion("viewEjoin <=", value, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinIn(List<Date> values) {
            addCriterion("viewEjoin in", values, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinNotIn(List<Date> values) {
            addCriterion("viewEjoin not in", values, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinBetween(Date value1, Date value2) {
            addCriterion("viewEjoin between", value1, value2, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewejoinNotBetween(Date value1, Date value2) {
            addCriterion("viewEjoin not between", value1, value2, "viewejoin");
            return (Criteria) this;
        }

        public Criteria andViewlevelIsNull() {
            addCriterion("viewLevel is null");
            return (Criteria) this;
        }

        public Criteria andViewlevelIsNotNull() {
            addCriterion("viewLevel is not null");
            return (Criteria) this;
        }

        public Criteria andViewlevelEqualTo(Integer value) {
            addCriterion("viewLevel =", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelNotEqualTo(Integer value) {
            addCriterion("viewLevel <>", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelGreaterThan(Integer value) {
            addCriterion("viewLevel >", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewLevel >=", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelLessThan(Integer value) {
            addCriterion("viewLevel <", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelLessThanOrEqualTo(Integer value) {
            addCriterion("viewLevel <=", value, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelIn(List<Integer> values) {
            addCriterion("viewLevel in", values, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelNotIn(List<Integer> values) {
            addCriterion("viewLevel not in", values, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelBetween(Integer value1, Integer value2) {
            addCriterion("viewLevel between", value1, value2, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("viewLevel not between", value1, value2, "viewlevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelIsNull() {
            addCriterion("viewSlevel is null");
            return (Criteria) this;
        }

        public Criteria andViewslevelIsNotNull() {
            addCriterion("viewSlevel is not null");
            return (Criteria) this;
        }

        public Criteria andViewslevelEqualTo(Integer value) {
            addCriterion("viewSlevel =", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelNotEqualTo(Integer value) {
            addCriterion("viewSlevel <>", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelGreaterThan(Integer value) {
            addCriterion("viewSlevel >", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewSlevel >=", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelLessThan(Integer value) {
            addCriterion("viewSlevel <", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelLessThanOrEqualTo(Integer value) {
            addCriterion("viewSlevel <=", value, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelIn(List<Integer> values) {
            addCriterion("viewSlevel in", values, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelNotIn(List<Integer> values) {
            addCriterion("viewSlevel not in", values, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelBetween(Integer value1, Integer value2) {
            addCriterion("viewSlevel between", value1, value2, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewslevelNotBetween(Integer value1, Integer value2) {
            addCriterion("viewSlevel not between", value1, value2, "viewslevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelIsNull() {
            addCriterion("viewElevel is null");
            return (Criteria) this;
        }

        public Criteria andViewelevelIsNotNull() {
            addCriterion("viewElevel is not null");
            return (Criteria) this;
        }

        public Criteria andViewelevelEqualTo(Integer value) {
            addCriterion("viewElevel =", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelNotEqualTo(Integer value) {
            addCriterion("viewElevel <>", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelGreaterThan(Integer value) {
            addCriterion("viewElevel >", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewElevel >=", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelLessThan(Integer value) {
            addCriterion("viewElevel <", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelLessThanOrEqualTo(Integer value) {
            addCriterion("viewElevel <=", value, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelIn(List<Integer> values) {
            addCriterion("viewElevel in", values, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelNotIn(List<Integer> values) {
            addCriterion("viewElevel not in", values, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelBetween(Integer value1, Integer value2) {
            addCriterion("viewElevel between", value1, value2, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewelevelNotBetween(Integer value1, Integer value2) {
            addCriterion("viewElevel not between", value1, value2, "viewelevel");
            return (Criteria) this;
        }

        public Criteria andViewosIsNull() {
            addCriterion("viewOS is null");
            return (Criteria) this;
        }

        public Criteria andViewosIsNotNull() {
            addCriterion("viewOS is not null");
            return (Criteria) this;
        }

        public Criteria andViewosEqualTo(Integer value) {
            addCriterion("viewOS =", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosNotEqualTo(Integer value) {
            addCriterion("viewOS <>", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosGreaterThan(Integer value) {
            addCriterion("viewOS >", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewOS >=", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosLessThan(Integer value) {
            addCriterion("viewOS <", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosLessThanOrEqualTo(Integer value) {
            addCriterion("viewOS <=", value, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosIn(List<Integer> values) {
            addCriterion("viewOS in", values, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosNotIn(List<Integer> values) {
            addCriterion("viewOS not in", values, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosBetween(Integer value1, Integer value2) {
            addCriterion("viewOS between", value1, value2, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewosNotBetween(Integer value1, Integer value2) {
            addCriterion("viewOS not between", value1, value2, "viewos");
            return (Criteria) this;
        }

        public Criteria andViewidxIsNull() {
            addCriterion("viewIdx is null");
            return (Criteria) this;
        }

        public Criteria andViewidxIsNotNull() {
            addCriterion("viewIdx is not null");
            return (Criteria) this;
        }

        public Criteria andViewidxEqualTo(Integer value) {
            addCriterion("viewIdx =", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxNotEqualTo(Integer value) {
            addCriterion("viewIdx <>", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxGreaterThan(Integer value) {
            addCriterion("viewIdx >", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxGreaterThanOrEqualTo(Integer value) {
            addCriterion("viewIdx >=", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxLessThan(Integer value) {
            addCriterion("viewIdx <", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxLessThanOrEqualTo(Integer value) {
            addCriterion("viewIdx <=", value, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxIn(List<Integer> values) {
            addCriterion("viewIdx in", values, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxNotIn(List<Integer> values) {
            addCriterion("viewIdx not in", values, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxBetween(Integer value1, Integer value2) {
            addCriterion("viewIdx between", value1, value2, "viewidx");
            return (Criteria) this;
        }

        public Criteria andViewidxNotBetween(Integer value1, Integer value2) {
            addCriterion("viewIdx not between", value1, value2, "viewidx");
            return (Criteria) this;
        }

        public Criteria andGmidIsNull() {
            addCriterion("gmID is null");
            return (Criteria) this;
        }

        public Criteria andGmidIsNotNull() {
            addCriterion("gmID is not null");
            return (Criteria) this;
        }

        public Criteria andGmidEqualTo(String value) {
            addCriterion("gmID =", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidNotEqualTo(String value) {
            addCriterion("gmID <>", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidGreaterThan(String value) {
            addCriterion("gmID >", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidGreaterThanOrEqualTo(String value) {
            addCriterion("gmID >=", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidLessThan(String value) {
            addCriterion("gmID <", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidLessThanOrEqualTo(String value) {
            addCriterion("gmID <=", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidLike(String value) {
            addCriterion("gmID like", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidNotLike(String value) {
            addCriterion("gmID not like", value, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidIn(List<String> values) {
            addCriterion("gmID in", values, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidNotIn(List<String> values) {
            addCriterion("gmID not in", values, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidBetween(String value1, String value2) {
            addCriterion("gmID between", value1, value2, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmidNotBetween(String value1, String value2) {
            addCriterion("gmID not between", value1, value2, "gmid");
            return (Criteria) this;
        }

        public Criteria andGmnameIsNull() {
            addCriterion("gmName is null");
            return (Criteria) this;
        }

        public Criteria andGmnameIsNotNull() {
            addCriterion("gmName is not null");
            return (Criteria) this;
        }

        public Criteria andGmnameEqualTo(String value) {
            addCriterion("gmName =", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameNotEqualTo(String value) {
            addCriterion("gmName <>", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameGreaterThan(String value) {
            addCriterion("gmName >", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameGreaterThanOrEqualTo(String value) {
            addCriterion("gmName >=", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameLessThan(String value) {
            addCriterion("gmName <", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameLessThanOrEqualTo(String value) {
            addCriterion("gmName <=", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameLike(String value) {
            addCriterion("gmName like", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameNotLike(String value) {
            addCriterion("gmName not like", value, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameIn(List<String> values) {
            addCriterion("gmName in", values, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameNotIn(List<String> values) {
            addCriterion("gmName not in", values, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameBetween(String value1, String value2) {
            addCriterion("gmName between", value1, value2, "gmname");
            return (Criteria) this;
        }

        public Criteria andGmnameNotBetween(String value1, String value2) {
            addCriterion("gmName not between", value1, value2, "gmname");
            return (Criteria) this;
        }

        public Criteria andLastgmidIsNull() {
            addCriterion("lastGmID is null");
            return (Criteria) this;
        }

        public Criteria andLastgmidIsNotNull() {
            addCriterion("lastGmID is not null");
            return (Criteria) this;
        }

        public Criteria andLastgmidEqualTo(String value) {
            addCriterion("lastGmID =", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidNotEqualTo(String value) {
            addCriterion("lastGmID <>", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidGreaterThan(String value) {
            addCriterion("lastGmID >", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidGreaterThanOrEqualTo(String value) {
            addCriterion("lastGmID >=", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidLessThan(String value) {
            addCriterion("lastGmID <", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidLessThanOrEqualTo(String value) {
            addCriterion("lastGmID <=", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidLike(String value) {
            addCriterion("lastGmID like", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidNotLike(String value) {
            addCriterion("lastGmID not like", value, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidIn(List<String> values) {
            addCriterion("lastGmID in", values, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidNotIn(List<String> values) {
            addCriterion("lastGmID not in", values, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidBetween(String value1, String value2) {
            addCriterion("lastGmID between", value1, value2, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmidNotBetween(String value1, String value2) {
            addCriterion("lastGmID not between", value1, value2, "lastgmid");
            return (Criteria) this;
        }

        public Criteria andLastgmnameIsNull() {
            addCriterion("lastGmName is null");
            return (Criteria) this;
        }

        public Criteria andLastgmnameIsNotNull() {
            addCriterion("lastGmName is not null");
            return (Criteria) this;
        }

        public Criteria andLastgmnameEqualTo(String value) {
            addCriterion("lastGmName =", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameNotEqualTo(String value) {
            addCriterion("lastGmName <>", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameGreaterThan(String value) {
            addCriterion("lastGmName >", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameGreaterThanOrEqualTo(String value) {
            addCriterion("lastGmName >=", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameLessThan(String value) {
            addCriterion("lastGmName <", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameLessThanOrEqualTo(String value) {
            addCriterion("lastGmName <=", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameLike(String value) {
            addCriterion("lastGmName like", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameNotLike(String value) {
            addCriterion("lastGmName not like", value, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameIn(List<String> values) {
            addCriterion("lastGmName in", values, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameNotIn(List<String> values) {
            addCriterion("lastGmName not in", values, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameBetween(String value1, String value2) {
            addCriterion("lastGmName between", value1, value2, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andLastgmnameNotBetween(String value1, String value2) {
            addCriterion("lastGmName not between", value1, value2, "lastgmname");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNull() {
            addCriterion("regDate is null");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNotNull() {
            addCriterion("regDate is not null");
            return (Criteria) this;
        }

        public Criteria andRegdateEqualTo(Date value) {
            addCriterion("regDate =", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotEqualTo(Date value) {
            addCriterion("regDate <>", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThan(Date value) {
            addCriterion("regDate >", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThanOrEqualTo(Date value) {
            addCriterion("regDate >=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThan(Date value) {
            addCriterion("regDate <", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThanOrEqualTo(Date value) {
            addCriterion("regDate <=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateIn(List<Date> values) {
            addCriterion("regDate in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotIn(List<Date> values) {
            addCriterion("regDate not in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateBetween(Date value1, Date value2) {
            addCriterion("regDate between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotBetween(Date value1, Date value2) {
            addCriterion("regDate not between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andLastdateIsNull() {
            addCriterion("lastDate is null");
            return (Criteria) this;
        }

        public Criteria andLastdateIsNotNull() {
            addCriterion("lastDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastdateEqualTo(Date value) {
            addCriterion("lastDate =", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateNotEqualTo(Date value) {
            addCriterion("lastDate <>", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateGreaterThan(Date value) {
            addCriterion("lastDate >", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastDate >=", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateLessThan(Date value) {
            addCriterion("lastDate <", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateLessThanOrEqualTo(Date value) {
            addCriterion("lastDate <=", value, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateIn(List<Date> values) {
            addCriterion("lastDate in", values, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateNotIn(List<Date> values) {
            addCriterion("lastDate not in", values, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateBetween(Date value1, Date value2) {
            addCriterion("lastDate between", value1, value2, "lastdate");
            return (Criteria) this;
        }

        public Criteria andLastdateNotBetween(Date value1, Date value2) {
            addCriterion("lastDate not between", value1, value2, "lastdate");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(Integer value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(Integer value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(Integer value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(Integer value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(Integer value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<Integer> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<Integer> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(Integer value1, Integer value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(Integer value1, Integer value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andEventsdateIsNull() {
            addCriterion("eventSdate is null");
            return (Criteria) this;
        }

        public Criteria andEventsdateIsNotNull() {
            addCriterion("eventSdate is not null");
            return (Criteria) this;
        }

        public Criteria andEventsdateEqualTo(Date value) {
            addCriterion("eventSdate =", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateNotEqualTo(Date value) {
            addCriterion("eventSdate <>", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateGreaterThan(Date value) {
            addCriterion("eventSdate >", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateGreaterThanOrEqualTo(Date value) {
            addCriterion("eventSdate >=", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateLessThan(Date value) {
            addCriterion("eventSdate <", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateLessThanOrEqualTo(Date value) {
            addCriterion("eventSdate <=", value, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateIn(List<Date> values) {
            addCriterion("eventSdate in", values, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateNotIn(List<Date> values) {
            addCriterion("eventSdate not in", values, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateBetween(Date value1, Date value2) {
            addCriterion("eventSdate between", value1, value2, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventsdateNotBetween(Date value1, Date value2) {
            addCriterion("eventSdate not between", value1, value2, "eventsdate");
            return (Criteria) this;
        }

        public Criteria andEventedateIsNull() {
            addCriterion("eventEdate is null");
            return (Criteria) this;
        }

        public Criteria andEventedateIsNotNull() {
            addCriterion("eventEdate is not null");
            return (Criteria) this;
        }

        public Criteria andEventedateEqualTo(Date value) {
            addCriterion("eventEdate =", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateNotEqualTo(Date value) {
            addCriterion("eventEdate <>", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateGreaterThan(Date value) {
            addCriterion("eventEdate >", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateGreaterThanOrEqualTo(Date value) {
            addCriterion("eventEdate >=", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateLessThan(Date value) {
            addCriterion("eventEdate <", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateLessThanOrEqualTo(Date value) {
            addCriterion("eventEdate <=", value, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateIn(List<Date> values) {
            addCriterion("eventEdate in", values, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateNotIn(List<Date> values) {
            addCriterion("eventEdate not in", values, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateBetween(Date value1, Date value2) {
            addCriterion("eventEdate between", value1, value2, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventedateNotBetween(Date value1, Date value2) {
            addCriterion("eventEdate not between", value1, value2, "eventedate");
            return (Criteria) this;
        }

        public Criteria andEventdelIsNull() {
            addCriterion("eventDel is null");
            return (Criteria) this;
        }

        public Criteria andEventdelIsNotNull() {
            addCriterion("eventDel is not null");
            return (Criteria) this;
        }

        public Criteria andEventdelEqualTo(Integer value) {
            addCriterion("eventDel =", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelNotEqualTo(Integer value) {
            addCriterion("eventDel <>", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelGreaterThan(Integer value) {
            addCriterion("eventDel >", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelGreaterThanOrEqualTo(Integer value) {
            addCriterion("eventDel >=", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelLessThan(Integer value) {
            addCriterion("eventDel <", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelLessThanOrEqualTo(Integer value) {
            addCriterion("eventDel <=", value, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelIn(List<Integer> values) {
            addCriterion("eventDel in", values, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelNotIn(List<Integer> values) {
            addCriterion("eventDel not in", values, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelBetween(Integer value1, Integer value2) {
            addCriterion("eventDel between", value1, value2, "eventdel");
            return (Criteria) this;
        }

        public Criteria andEventdelNotBetween(Integer value1, Integer value2) {
            addCriterion("eventDel not between", value1, value2, "eventdel");
            return (Criteria) this;
        }

        public Criteria andVisitIsNull() {
            addCriterion("visit is null");
            return (Criteria) this;
        }

        public Criteria andVisitIsNotNull() {
            addCriterion("visit is not null");
            return (Criteria) this;
        }

        public Criteria andVisitEqualTo(Integer value) {
            addCriterion("visit =", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitNotEqualTo(Integer value) {
            addCriterion("visit <>", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitGreaterThan(Integer value) {
            addCriterion("visit >", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitGreaterThanOrEqualTo(Integer value) {
            addCriterion("visit >=", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitLessThan(Integer value) {
            addCriterion("visit <", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitLessThanOrEqualTo(Integer value) {
            addCriterion("visit <=", value, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitIn(List<Integer> values) {
            addCriterion("visit in", values, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitNotIn(List<Integer> values) {
            addCriterion("visit not in", values, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitBetween(Integer value1, Integer value2) {
            addCriterion("visit between", value1, value2, "visit");
            return (Criteria) this;
        }

        public Criteria andVisitNotBetween(Integer value1, Integer value2) {
            addCriterion("visit not between", value1, value2, "visit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manage_event_notice
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 06 15:02:24 KST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}