package com.nhn.base.notice.bean;

public class NoticeSubKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.notice_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private Integer noticeIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_notice_sub.sub_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    private Integer subIdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.notice_idx
     *
     * @return the value of manage_event_notice_sub.notice_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public Integer getNoticeIdx() {
        return noticeIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.notice_idx
     *
     * @param noticeIdx the value for manage_event_notice_sub.notice_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setNoticeIdx(Integer noticeIdx) {
        this.noticeIdx = noticeIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_notice_sub.sub_idx
     *
     * @return the value of manage_event_notice_sub.sub_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public Integer getSubIdx() {
        return subIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_notice_sub.sub_idx
     *
     * @param subIdx the value for manage_event_notice_sub.sub_idx
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    public void setSubIdx(Integer subIdx) {
        this.subIdx = subIdx;
    }
}