package com.nhn.base.notice.mapper;

import com.nhn.base.notice.bean.NoticeSub;
import com.nhn.base.notice.bean.NoticeSubExample;
import com.nhn.base.notice.bean.NoticeSubKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int countByExample(NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int deleteByExample(NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int deleteByPrimaryKey(NoticeSubKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int insert(NoticeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int insertSelective(NoticeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    List<NoticeSub> selectByExampleWithBLOBs(NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    List<NoticeSub> selectByExample(NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    NoticeSub selectByPrimaryKey(NoticeSubKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByExampleSelective(@Param("record") NoticeSub record, @Param("example") NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") NoticeSub record, @Param("example") NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByExample(@Param("record") NoticeSub record, @Param("example") NoticeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByPrimaryKeySelective(NoticeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByPrimaryKeyWithBLOBs(NoticeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice_sub
     *
     * @mbggenerated Mon Feb 06 15:02:22 KST 2017
     */
    int updateByPrimaryKey(NoticeSub record);
}