package com.nhn.base.notice.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.nhn.base.notice.bean.Notice;
import com.nhn.base.notice.bean.NoticeExample;
import com.nhn.base.notice.bean.PopupNotice;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    List<Notice> selectByExampleWithBLOBs(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    Notice selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_notice
     *
     * @mbggenerated Mon Feb 06 15:02:24 KST 2017
     */
    int updateByPrimaryKey(Notice record);

    List<PopupNotice> selectPopupNotice(HashMap<String, Object> param);

    Notice selectNoticeEventByIdx(HashMap<String, Object> param);

    List<PopupNotice> selectLoadingImgList(HashMap<String, Object> param);
}