package com.nhn.www.preregist.bean;

import java.util.Date;

public class SnsReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.seq
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.userkey
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.snsname
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private String snsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.local
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private String local;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.regdate
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_reply.msg
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.seq
     *
     * @return the value of sns_reply.seq
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.seq
     *
     * @param seq the value for sns_reply.seq
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.userkey
     *
     * @return the value of sns_reply.userkey
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.userkey
     *
     * @param userkey the value for sns_reply.userkey
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.snsname
     *
     * @return the value of sns_reply.snsname
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public String getSnsname() {
        return snsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.snsname
     *
     * @param snsname the value for sns_reply.snsname
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setSnsname(String snsname) {
        this.snsname = snsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.local
     *
     * @return the value of sns_reply.local
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.local
     *
     * @param local the value for sns_reply.local
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setLocal(String local) {
        this.local = local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.regdate
     *
     * @return the value of sns_reply.regdate
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.regdate
     *
     * @param regdate the value for sns_reply.regdate
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_reply.msg
     *
     * @return the value of sns_reply.msg
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_reply.msg
     *
     * @param msg the value for sns_reply.msg
     *
     * @mbggenerated Sun Mar 19 12:55:57 KST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }
}