package com.nhn.www.preregist.bean;

import java.util.Date;

public class SnsShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.seq
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.code
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.snsname
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private String snsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.userkey
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.local
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private String local;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_share.regdate
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    private Date regdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.seq
     *
     * @return the value of sns_share.seq
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.seq
     *
     * @param seq the value for sns_share.seq
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.code
     *
     * @return the value of sns_share.code
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.code
     *
     * @param code the value for sns_share.code
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.snsname
     *
     * @return the value of sns_share.snsname
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public String getSnsname() {
        return snsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.snsname
     *
     * @param snsname the value for sns_share.snsname
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setSnsname(String snsname) {
        this.snsname = snsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.userkey
     *
     * @return the value of sns_share.userkey
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.userkey
     *
     * @param userkey the value for sns_share.userkey
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.local
     *
     * @return the value of sns_share.local
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.local
     *
     * @param local the value for sns_share.local
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setLocal(String local) {
        this.local = local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_share.regdate
     *
     * @return the value of sns_share.regdate
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_share.regdate
     *
     * @param regdate the value for sns_share.regdate
     *
     * @mbggenerated Fri Mar 17 17:25:05 KST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
}