package com.nhn.base.coupon.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.nhn.base.coupon.bean.CouponLog;
import com.nhn.base.coupon.bean.CouponLogExample;
import com.nhn.base.coupon.bean.CouponLogExtends;

public interface CouponLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int countByExample(CouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int deleteByExample(CouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int deleteByPrimaryKey(Long idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int insert(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int insertSelective(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    List<CouponLog> selectByExample(CouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    CouponLog selectByPrimaryKey(Long idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int updateByExampleSelective(@Param("record") CouponLog record, @Param("example") CouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int updateByExample(@Param("record") CouponLog record, @Param("example") CouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int updateByPrimaryKeySelective(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_event_coupon_log
     *
     * @mbggenerated Mon Feb 06 15:02:16 KST 2017
     */
    int updateByPrimaryKey(CouponLog record);

    int myUsedCouponListCount(HashMap<String, Object> param);

    List<CouponLogExtends> myUsedCouponList(HashMap<String, Object> param);
}