package com.nhn.base.coupon.bean;

public class CouponItemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_coupon_item.event_idx
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    private Integer eventIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event_coupon_item.num
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_coupon_item.event_idx
     *
     * @return the value of manage_event_coupon_item.event_idx
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    public Integer getEventIdx() {
        return eventIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_coupon_item.event_idx
     *
     * @param eventIdx the value for manage_event_coupon_item.event_idx
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    public void setEventIdx(Integer eventIdx) {
        this.eventIdx = eventIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event_coupon_item.num
     *
     * @return the value of manage_event_coupon_item.num
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event_coupon_item.num
     *
     * @param num the value for manage_event_coupon_item.num
     *
     * @mbggenerated Mon Feb 06 15:02:12 KST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}