package com.nhn.base.coupon.bean;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.idx
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.ctype
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private Integer ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.cname
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.startDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.endDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.charID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String charid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.msgID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.gmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String gmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.gmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String gmname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.regDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.lastgmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String lastgmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.lastgmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String lastgmname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.lastDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private Date lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.url
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.memo
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.del
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.codeName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String codename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.tempcode1
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String tempcode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.tempcode2
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String tempcode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_event.tempcode3
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    private String tempcode3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.idx
     *
     * @return the value of manage_event.idx
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.idx
     *
     * @param idx the value for manage_event.idx
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.ctype
     *
     * @return the value of manage_event.ctype
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.ctype
     *
     * @param ctype the value for manage_event.ctype
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.cname
     *
     * @return the value of manage_event.cname
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.cname
     *
     * @param cname the value for manage_event.cname
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.startDate
     *
     * @return the value of manage_event.startDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.startDate
     *
     * @param startdate the value for manage_event.startDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.endDate
     *
     * @return the value of manage_event.endDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.endDate
     *
     * @param enddate the value for manage_event.endDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.charID
     *
     * @return the value of manage_event.charID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getCharid() {
        return charid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.charID
     *
     * @param charid the value for manage_event.charID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setCharid(String charid) {
        this.charid = charid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.msgID
     *
     * @return the value of manage_event.msgID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.msgID
     *
     * @param msgid the value for manage_event.msgID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.gmID
     *
     * @return the value of manage_event.gmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getGmid() {
        return gmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.gmID
     *
     * @param gmid the value for manage_event.gmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setGmid(String gmid) {
        this.gmid = gmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.gmName
     *
     * @return the value of manage_event.gmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getGmname() {
        return gmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.gmName
     *
     * @param gmname the value for manage_event.gmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setGmname(String gmname) {
        this.gmname = gmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.regDate
     *
     * @return the value of manage_event.regDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.regDate
     *
     * @param regdate the value for manage_event.regDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.lastgmID
     *
     * @return the value of manage_event.lastgmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getLastgmid() {
        return lastgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.lastgmID
     *
     * @param lastgmid the value for manage_event.lastgmID
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setLastgmid(String lastgmid) {
        this.lastgmid = lastgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.lastgmName
     *
     * @return the value of manage_event.lastgmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getLastgmname() {
        return lastgmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.lastgmName
     *
     * @param lastgmname the value for manage_event.lastgmName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setLastgmname(String lastgmname) {
        this.lastgmname = lastgmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.lastDate
     *
     * @return the value of manage_event.lastDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.lastDate
     *
     * @param lastdate the value for manage_event.lastDate
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.url
     *
     * @return the value of manage_event.url
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.url
     *
     * @param url the value for manage_event.url
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.memo
     *
     * @return the value of manage_event.memo
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.memo
     *
     * @param memo the value for manage_event.memo
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.del
     *
     * @return the value of manage_event.del
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.del
     *
     * @param del the value for manage_event.del
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.codeName
     *
     * @return the value of manage_event.codeName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getCodename() {
        return codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.codeName
     *
     * @param codename the value for manage_event.codeName
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setCodename(String codename) {
        this.codename = codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.tempcode1
     *
     * @return the value of manage_event.tempcode1
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getTempcode1() {
        return tempcode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.tempcode1
     *
     * @param tempcode1 the value for manage_event.tempcode1
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setTempcode1(String tempcode1) {
        this.tempcode1 = tempcode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.tempcode2
     *
     * @return the value of manage_event.tempcode2
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getTempcode2() {
        return tempcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.tempcode2
     *
     * @param tempcode2 the value for manage_event.tempcode2
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setTempcode2(String tempcode2) {
        this.tempcode2 = tempcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_event.tempcode3
     *
     * @return the value of manage_event.tempcode3
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public String getTempcode3() {
        return tempcode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_event.tempcode3
     *
     * @param tempcode3 the value for manage_event.tempcode3
     *
     * @mbggenerated Mon Feb 06 15:02:19 KST 2017
     */
    public void setTempcode3(String tempcode3) {
        this.tempcode3 = tempcode3;
    }
}