package com.nhn.www.preregist.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.nhn.www.preregist.bean.PreRegist;
import com.nhn.www.preregist.bean.PreRegistExample;
import com.nhn.www.preregist.bean.PreRegistStatus;

public interface PreRegistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int countByExample(PreRegistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int deleteByExample(PreRegistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int deleteByPrimaryKey(String userkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int insert(PreRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int insertSelective(PreRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    List<PreRegist> selectByExample(PreRegistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    PreRegist selectByPrimaryKey(String userkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int updateByExampleSelective(@Param("record") PreRegist record, @Param("example") PreRegistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int updateByExample(@Param("record") PreRegist record, @Param("example") PreRegistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int updateByPrimaryKeySelective(PreRegist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist
     *
     * @mbggenerated Fri Mar 17 11:54:08 KST 2017
     */
    int updateByPrimaryKey(PreRegist record);

    List<PreRegistStatus> getRegistStatus();
}