package com.nhn.www.preregist.mapper;

import com.nhn.www.preregist.bean.PreRegistTry;
import com.nhn.www.preregist.bean.PreRegistTryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreRegistTryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int countByExample(PreRegistTryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int deleteByExample(PreRegistTryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int deleteByPrimaryKey(Long seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int insert(PreRegistTry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int insertSelective(PreRegistTry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    List<PreRegistTry> selectByExample(PreRegistTryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    PreRegistTry selectByPrimaryKey(Long seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int updateByExampleSelective(@Param("record") PreRegistTry record, @Param("example") PreRegistTryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int updateByExample(@Param("record") PreRegistTry record, @Param("example") PreRegistTryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int updateByPrimaryKeySelective(PreRegistTry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_regist_try
     *
     * @mbggenerated Fri Mar 17 11:54:06 KST 2017
     */
    int updateByPrimaryKey(PreRegistTry record);
}