package com.nhn.www.event.mapper;

import com.nhn.www.event.bean.FlowerEventInfoByDate;
import com.nhn.www.event.bean.FlowerEventInfoByDateExample;
import com.nhn.www.event.bean.FlowerEventInfoByDateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowerEventInfoByDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int countByExample(FlowerEventInfoByDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int deleteByExample(FlowerEventInfoByDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int deleteByPrimaryKey(FlowerEventInfoByDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int insert(FlowerEventInfoByDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int insertSelective(FlowerEventInfoByDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    List<FlowerEventInfoByDate> selectByExample(FlowerEventInfoByDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    FlowerEventInfoByDate selectByPrimaryKey(FlowerEventInfoByDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int updateByExampleSelective(@Param("record") FlowerEventInfoByDate record, @Param("example") FlowerEventInfoByDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int updateByExample(@Param("record") FlowerEventInfoByDate record, @Param("example") FlowerEventInfoByDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int updateByPrimaryKeySelective(FlowerEventInfoByDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flower_event_info_bydate
     *
     * @mbggenerated Mon Apr 10 16:52:11 KST 2017
     */
    int updateByPrimaryKey(FlowerEventInfoByDate record);
}