package com.nhn.elog.bean;

import java.util.Date;

public class AbsEventlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.LogTime
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.Log
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private String log;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.UserID
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.GameNo
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer gameno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.Lv
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer lv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.Exp
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.FreeGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Long freegold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.RealGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Long realgold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.FP
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer fp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.FreeGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer freegem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.RealGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private Integer realgem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abs_event_log.Param1
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    private String param1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.LogTime
     *
     * @return the value of abs_event_log.LogTime
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.LogTime
     *
     * @param logtime the value for abs_event_log.LogTime
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.Log
     *
     * @return the value of abs_event_log.Log
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.Log
     *
     * @param log the value for abs_event_log.Log
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setLog(String log) {
        this.log = log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.UserID
     *
     * @return the value of abs_event_log.UserID
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.UserID
     *
     * @param userid the value for abs_event_log.UserID
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.GameNo
     *
     * @return the value of abs_event_log.GameNo
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getGameno() {
        return gameno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.GameNo
     *
     * @param gameno the value for abs_event_log.GameNo
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setGameno(Integer gameno) {
        this.gameno = gameno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.Lv
     *
     * @return the value of abs_event_log.Lv
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getLv() {
        return lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.Lv
     *
     * @param lv the value for abs_event_log.Lv
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setLv(Integer lv) {
        this.lv = lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.Exp
     *
     * @return the value of abs_event_log.Exp
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.Exp
     *
     * @param exp the value for abs_event_log.Exp
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.FreeGold
     *
     * @return the value of abs_event_log.FreeGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Long getFreegold() {
        return freegold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.FreeGold
     *
     * @param freegold the value for abs_event_log.FreeGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setFreegold(Long freegold) {
        this.freegold = freegold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.RealGold
     *
     * @return the value of abs_event_log.RealGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Long getRealgold() {
        return realgold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.RealGold
     *
     * @param realgold the value for abs_event_log.RealGold
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setRealgold(Long realgold) {
        this.realgold = realgold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.FP
     *
     * @return the value of abs_event_log.FP
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getFp() {
        return fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.FP
     *
     * @param fp the value for abs_event_log.FP
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setFp(Integer fp) {
        this.fp = fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.FreeGem
     *
     * @return the value of abs_event_log.FreeGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getFreegem() {
        return freegem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.FreeGem
     *
     * @param freegem the value for abs_event_log.FreeGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setFreegem(Integer freegem) {
        this.freegem = freegem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.RealGem
     *
     * @return the value of abs_event_log.RealGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public Integer getRealgem() {
        return realgem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.RealGem
     *
     * @param realgem the value for abs_event_log.RealGem
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setRealgem(Integer realgem) {
        this.realgem = realgem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abs_event_log.Param1
     *
     * @return the value of abs_event_log.Param1
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abs_event_log.Param1
     *
     * @param param1 the value for abs_event_log.Param1
     *
     * @mbggenerated Mon Apr 10 15:21:10 KST 2017
     */
    public void setParam1(String param1) {
        this.param1 = param1;
    }
}